repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
     - id: check-yaml
     - id: end-of-file-fixer
     - id: trailing-whitespace
     - id: check-added-large-files
       # The notebooks in this path go through nbstrip_full filter
       exclude: "^notebooks/.*.ipynb$"
  - repo: local
    hooks:
     # We use local for the following as we will have it for dev setup anyway, find discussion at https://stackoverflow.com/questions/67795922/understanding-how-to-configure-pre-commit-with-repo-local
     # I think I understand that it may be better to use the git repos but in our case with uv and setup.sh, we can just use local, this way we also have the same versions
     - id: isort
       name: isort
       language: system
       entry: uv run isort
    #  - id: black
    #    name: black
    #    language: system
    #    entry: uv run black
     - id: ruff
       name: ruff-check
       language: system
       entry: uv run ruff check
       types_or: [ python, pyi, jupyter ]
       args: [ --fix ]
     - id: ruff-format
       name: ruff-format
       language: system
       entry: uv run ruff format
       types_or: [ python, pyi, jupyter ]
     - id: mypy
       name: mypy
       language: system
       entry: uv run mypy
       types_or: [ python ]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
     - id: shellcheck
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.5
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-export
