__all__ = [
    "FORMAT_ISO_DATE",
    "FORMAT_YYYYMMDD_DATE",
    "FRYER_ENV_PATH_DATA",
    "FRYER_ENV_PATH_LOG",
    "FRYER_ENV_TODAY",
    "TIMEOUT_LONG",
    "TIMEOUT_SHORT",
    "YYYYMMDD",
]


FRYER_ENV_PATH_LOG: str = "FRYER_ENV_PATH_LOG"
FRYER_ENV_PATH_DATA: str = "FRYER_ENV_PATH_DATA"
FRYER_ENV_TODAY: str = "FRYER_ENV_TODAY"


YYYYMMDD: str = "YYYY-MM-DD"
FORMAT_ISO_DATE: str = "%Y-%m-%d"
FORMAT_YYYYMMDD_DATE: str = "%Y%m%d"


TIMEOUT_LONG: int = 600
TIMEOUT_SHORT: int = 60
