__all__ = [
    "FRYER_ENV_PATH_LOG",
    "FRYER_ENV_PATH_DATA",
    "FRYER_ENV_TODAY",
    "YYYYMMDD",
    "FORMAT_ISO_DATE",
    "FORMAT_YYYYMMDD_DATE",
]


FRYER_ENV_PATH_LOG = "FRYER_ENV_PATH_LOG"
FRYER_ENV_PATH_DATA = "FRYER_ENV_PATH_DATA"
FRYER_ENV_TODAY = "FRYER_ENV_TODAY"


YYYYMMDD = "YYYY-MM-DD"
FORMAT_ISO_DATE = "%Y-%m-%d"
FORMAT_YYYYMMDD_DATE = "%Y%m%d"
