name: ChipShop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  chip-shop-main:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv venv

      - name: Install the project
        run: uv sync

      - name: Run tests
        # For example, using `pytest`
        run: ./run_tests.sh
