name: ChipShop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  chip-shop-main:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run setup script
        run: ./setup.sh

      - name: Run the pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        # For example, using `pytest`
        run: ./run_tests.sh
